### PR TITLE
Remove parenting to add Child Of constraint

### PR DESCRIPTION
**Pull request by janga1997**
The only minor thing which bothers me is the number of objects now cluttered in the top-right list.
But it does work as before, and solves our problem of parenting-scaling.

### CODE REVIEW

**Comment by zanoni-mbdyn** [comment]
Yeah, there's not very much we can do about that, I fear... 
The only thing that comes to my mind is to use groups: it will not solve the cluttering problem in the default `All Scenes` panel, but the list will be much more tidy in the `Groups` list. 

We could use the same categories of the input manual:

- Nodes
    - Structural Nodes
- Elements
    - Beams
    - Bodies
    - Forces
    - Joints
    - Plates

The idea is that we could then add other subgroups as we support more node or element types.

**Comment by janga1997** [comment]
So, I have looked around for a while, and I haven't found a good solution for nested groups (Sub grouping withing groups) .
All I found is a **paid** addon. 
[Addon](https://blenderartists.org/forum/archive/index.php/t-381665.html)

**Comment by janga1997** [comment]
Alright, that takes care of the grouping, although not the nested grouping.

**Comment by zanoni-mbdyn** [comment]
OK, no problem with nested grouping: just get rid of the top "Nodes" and "Elements" groups. 
It is enough to use the second level groups of my previous comment.

**Comment by janga1997** [comment]
I already pushed the commits. this PR is done IMO.

**Comment by zanoni-mbdyn** [comment]
ok, sorry: I'm testing now

**Comment by zanoni-mbdyn** [comment]
I'm very bothered by the fact that there are no nested groups... Now beams and rods cause a lot of cluttering also in the Groups list. I don't like it. 

We should find a better solution, let me think a bit on the issue.

**Comment by zanoni-mbdyn** [comment]
What about we do what is currently done for beams, for example, for all the elements, and get rid of the "higher" groups? 

Let a group for a single element type contain all the objects that are somehow related to that element visualization.

And let's live with the cluttering in the main Scene Outliner.

**Comment by janga1997** [comment]
@zanoni-mbdyn 
I think I took care of all the elements.
Update: If you are okay with the groups, don't merge this yet. The `Child_of` constraint works in a different way than parenting, i.e. they automatically take care of applying the parent element's rotation/position

```
        revjOBJ.rotation_quaternion = \
                n1OBJ.rotation_quaternion * Quaternion(( q1[0], q1[1], q1[2], q1[3] ))

AND

        p1 = n1OBJ.location + R1*Vector(( f1[0], f1[1], f1[2] ))

```
I am working on the new elements (linear and angular elements), and will get on this right away.

**Pull request merged**
