### PR TITLE
Joint elements

### PR DESCRIPTION
**Pull request by janga1997**
1. In the info_draw function for inplane, I haven't added the offsets yet. Would it be better to display the direction of normal to the plane, or the orientation offsets from node1 ?
2. I've added *.blend1 files to be ignored in the `.gitignore`. They interfere in our git workflow.
3. I will add a couple other joints to this, instead of creating a new PR for each.

### CODE REVIEW

**Comment by zanoni-mbdyn** [comment]
1. The normal (espressed in the reference frame of Node 1) is perfect
2. Good. I put them in my `.git/info/exclude` file but I always forgot to put them in a global `.gitignore`
3. OK

**Comment by janga1997** [comment]
I noticed the max_elem_import and the min_elem_import variables both stayed at zero, which was the reason adding elements to the scene in batches (through the `Add all the elements to the scene` and `import elements by type` buttons did not work).
So, I added in some lines analogous to the nodes equivalent, although it is not exactly the same.

In nodes, the the `int_label` designates the numbering of the node in general.
In elements, the `int_label` designates the numbering of the element in **its type**.

So, while `max_node_import` reflects the total number of nodes, `max_elem_import` reflects the maximum number of elements in any type. It does work, but it is a misleading number.

**Comment by janga1997** [comment]
@zanoni-mbdyn And, I'm facing trouble with the displaying the normal direction of the inplane joint.

This is what i tried to do:
1. The inplane joint model in `joints.blend` has a normal in the direction Vector((0, 0, 1))
2. I get the rotation of the  inplane joint in the scene from `inplaneJoint.rotation_euler`
3. I rotate the default normal direction (`(0, 0, 1)`, with the amount of rotation of the inplane joint)

`dummy = Vector((0, 0, 1))
rotation = inplaneJoint.rotation_euler
dummy.rotate(rotation)
print (dummy) 
`
But the final result never seems to reflect the normal direction of the plane. You can try it out, as I've added it in the latest commit.

**Comment by janga1997** [comment]
In the projects page, `axial rotation` joint has been wrongly flagged as having no log output. It does.
It is the linear (velocity, acceleration) and the angular (velocity, acceleration) joints that have no log output.

**Comment by zanoni-mbdyn** [comment]
@janga1997 thanks for noticing, I'll update the project's page. 
Also I'm going to review and test this PR today.

**Comment by janga1997** [comment]
When the **`revolute rotation`** joint is logged in the log file, it doesn't seem to log the offsets, causing the element to always spawn at the first node.
I'm sure about the position offsets not being logged, haven't tried the orientation offsets.

**Comment by zanoni-mbdyn** [comment]
Looking at the MBDyn code, it should always log null offsets. Since it doesn't introduce any positional constraint, the offsets are inessential...

**Comment by zanoni-mbdyn** [comment]
Please see my review. Whatch out because you have repeatedly set the parenting to the wrong objects (you parent the object of node 2 to the one of node 1, whilst you want to set it between the mesh object of the joint and the node 1 object). 

Also, please always create the empty objects representing the joint internal reference frames.

**Comment by janga1997** [comment]
> Also, please always create the empty objects representing the joint internal reference frames.

I will do that in just a bit.

I just have a little problem with the distance joint. Since the `distance joint` doesn't really have a orientation of its own, and I suppose it just sets a distance constraint in the straight line formed by the two nodes? (Do correct me if I am wrong).

Right now, I am just spawning the distance joint at node_1 (with offset), and the orientation doesn't look right, as it's supposed to be in the direction of the line joining the two nodes. Could/Should we do something about it?

**Comment by zanoni-mbdyn** [comment]
The distance is acting along the line connecting the two points defined by the offsets with respect to the nodes it connects. 

Take a look at the rod joint: you might want to do something very similar to visualize the distance joint. You might use exactly the same representation, just adding a small circle as a bevel object to the line that joints the 2 connection points, and maybe two small spheres at the points themselves.

**Comment by janga1997** [comment]
@zanoni-mbdyn **`viscous body`** and **`beam slider`** don't seem to be logged. (They aren't mentioned in the MBDyn input manual. Correct me if I am wrong.)

**Comment by zanoni-mbdyn** [comment]
I don't know about logging (I'll check asap) but they certainly are
mentioned in the input manual.

Il 14 giu 2017 13:40, "VSN Reddy Janga" <notifications@github.com> ha
scritto:

**Comment by janga1997** [comment]
I mean, they are mentioned in the input manual, but they are not mentioned in the `Log File Format` section, which details all the elements currently being logged.

**Comment by zanoni-mbdyn** [comment]
OK, now I get it. Just leave them aside.
Can you edit the projects pages? In case you can't, I'll try to see how I can give you the edit privileges, so that you can mark the joints as not having `.log` output yourself.

**Comment by zanoni-mbdyn** [comment]
About the distance joint: this is not what I had in mind. 
I want the two spheres to be at the two points connected by the distance joint (points defined by offset 1 w.r.t. node 1 and offset 2 w.r.t. node 2) and the cylinder between them to be generated starting from straight line segment in 3D. 

That's why I suggested you to take a look at the rod joint code: you could start from that precise code, that results in straight curve being drawn in the scene, with its ends connected through hooks to the respective nodes at the correct points. 

You could just add a circular bevel (i.e. a section) to the curve objects, and then add the two spheres.

**Comment by janga1997** [comment]
@zanoni-mbdyn 
took me a while, but I think the distance joint works exactly as you wanted.
I created a cylindrical rod using the same code of `rodjlib.py`, converted it into a MESH object, attached two spheres to the ends, and then joined the three (cylindrical rod and two spherical ends),
and finally deleted the faces to make it an empty.

**Comment by janga1997** [comment]
The brake joint I added is a ridiculous oversimplification of an actual one, but I hope it works for our purposes.
screenshot from 2017-06-18 19-06-45

**Comment by zanoni-mbdyn** [comment]
@janga1997 about the distance: now it works well in the initial assembly, but it doesn't update it configuration to show a variable distance being imposed. It just stays in the initial configuration for the whole animation. 

See the attached video: what i'd like to see is the ends of the distance joint (the spheres) follow the nodes they are attached to. In this example, I'd like to see the two spheres that are originally coincident with the selected nodes follow them up to the final position, with the cylinder representing the distance reducing its length to almost zero in the final configuration.

**Comment by zanoni-mbdyn** [comment]
@janga1997 about the brake joint: I know it is a small detail, but it would be nice to have the disk rotating with node 2 :)

**Comment by janga1997** [comment]
@zanoni-mbdyn I was under the impression that the distance joint maintained a constant distance, which is why I converted it into a mesh object, and that is why its dimensions remain constant.

**Comment by zanoni-mbdyn** [comment]
@janga1997 nope, you can assign a drive (i.e. a time-dependence) to the distance magnitude. 
Actually, it is very handy to do it to "let models assemble themselves" sometimes...

**Comment by janga1997** [comment]
@zanoni-mbdyn If we want the brake joint to rotate with node_2, we will have to set node_2 as its parent, instead of node_1.
I assumed I was to follow the convention of always setting node_1 as the parent.

**OR**

We hook the brake joint to node_2, and the rotation of node_2 will be reflected in the brake joint. I'm not sure how parenting to node_1 and hooking to node_2 will make it behave.

**Comment by zanoni-mbdyn** [comment]
You're right, but in this case, I'll follow a different path: what if we subdivide the brake mesh into two objects? The caliper stays with node_1, and the disk with node_2.

We could just not parent anyone this time, like we do for rods and beams...
It would certainly look better this way.

**Comment by janga1997** [comment]
I think the brake joint, and the distance joint works as you wanted them to.

**Comment by zanoni-mbdyn** [comment]
Yes, they do. Fine job :)

**Comment by zanoni-mbdyn** [comment]
Are we ready to merge or are you still working on some other type of joint?

**Comment by janga1997** [comment]
@zanoni-mbdyn Nope. I am working on the deformable joints in the other PR.
This is ready to merge for me.

**Comment by zanoni-mbdyn** [comment]
Good. Merged.

**Pull request merged**
