### PR TITLE
Add Prismatic element

### PR DESCRIPTION
**Pull request by janga1997**

### CODE REVIEW

**Comment by janga1997** [comment]
@zanoni-mbdyn I was thinking about moving onto **In Plane Joint**, since it seems straightforward enough.
The mesh for In plane Joint could be a block upon a larger block, with two straight arrows representing the two linear degrees of freedom, and one curved arrow representing the rotational degree of freedom about the common normal as axis.
Edit: [A link](https://cad.onshape.com/documents/d9475fdf58d6ba100604aec1/w/45b97e0eedc28472694b82e0/e/dc969193d9a2c72020e2b2de) is always better.

**Comment by zanoni-mbdyn** [comment]
@janga1997 Uhm, yes it could work. Just make the "plane" object more like an actual plane. Maybe when you import it in Blender you could just remove any thickness from it and leave just a single face in the mesh

**Comment by janga1997** [comment]
@zanoni-mbdyn You mean a block on a plane (without any thickness), instead of just a larger object that it is right now ?

**Comment by zanoni-mbdyn** [comment]
Yes. Trying out your PR I've found a bug in re-importing an existing joint,
that affects multiple elements.
I'm fixing it right now.

2017-06-05 15:40 GMT+02:00 VSN Reddy Janga <notifications@github.com>:

**Comment by zanoni-mbdyn** [comment]
Good start on the Prismatic joint. I'd like for you to make a few additions before I merge:

- please add an empty axes object representing the second reference frame used by the joint (the one defined with respect to node 2): it helps debugging a model that fails during the initial assembly;
- add an `info_draw` operator;
- [optional] if you feel like it, it would be nice to add also a `write_operator` (see `rodjlib.py`, for example) that writes the updated MBDyn input for the element based on how the user has moved the joint mesh in the Blender scene.

**Comment by zanoni-mbdyn** [comment]
I've modified a bit the `info_draw` function and removed the parsing of the displacement offsets, since they are always null, and merged.

**Pull request merged**
